version: "3"
services:
  app:
    build:
      context: ./app
    volumes:
      - ./app:/app
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - ./postgres/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql

  nginx:
    build:
      context: ./nginx
    depends_on:
      - app
    ports:
      - "80:80"

